### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by tokarevart** [yantsant/tensor#3]
Hi, i have been looking through code and i think i have found a memory leak? Or i didn't notice something and am mistaken?
If there's really a memory leak then i'd like to suggest to use less raw pointers where it can be avoided, like in that line of code (or is there a need for it and i didn't notice something?).
https://github.com/yantsant/tensor/blob/d582ea69e6a00c31ca6e1c36d3b372d97985c701/tensor/main.cpp#L122
https://github.com/yantsant/tensor/blob/d582ea69e6a00c31ca6e1c36d3b372d97985c701/tensor/main.cpp#L132

I have also found in the following lines unnecessary use of raw pointers, which is i think is a bad practice and can leak to a memory leaks as i mentioned above. There's this thing called RAII in C++ (and not only), which makes objects creation and deletion much easier and provides memory guarantees (like for example that obejct will be correctly deallocated when it's life time is over, like at the end of a fuction or a curly braced block)
https://github.com/yantsant/tensor/blob/d582ea69e6a00c31ca6e1c36d3b372d97985c701/tensor/main.cpp#L139

When i was working with C++ (and while have been learning/working with Rust) i have formulated some rules of writing code and working with pointers in C++ and i'd like to share some of them:
1. Every object/value is either placed on stack or owned by a smart pointer (but never only placed on a heap with only raw pointers pointng on it). 
2. Only ever take a raw pointer of a value if the value is already owned and you're absolutely sure the value will not be deallocated before every raw pointer's life time (the last dereferencing is done before the object is deallocated) is over. See on a topic of lifetimes in Rust to know how we in Rust solve these memory management issues.

It's better if objects (where possible) are never created with `new` statement and therefore never deallocated with `delete`, which i think is possible for most cases if above mentioned rules are taken into account and smart pointers created only with `std::make_unique` and `std::make_shared`.

**Comment by yantsant** [comment]
Hi, you are right about using of raw pointers. But source file `main.cpp` just contains examples of creating and using library objects and it may be unsafe. In these examples all raw pointers under control. There is only one place Inside the library when raw pointers are used - protected part of base class `container`. It would be better to change it to `std::unique_ptr`.
